version: "2"

services:

  react:
    container_name: react-app
    build: .
    environment:
        NODE_ENV: development
    ports:
        - "3000:3000"
    #volumes:
        #- ./app:/usr/src/app
